# {{ if eq .Cluster.ConfigItems.kubelet_summary_metrics_enabled "true" }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubelet-summary-metrics
  namespace: kube-system
  labels:
    application: kubernetes
    component: kubelet-summary-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-summary-metrics
  labels:
    application: kubernetes
    component: kubelet-summary-metrics
rules:
- apiGroups: [""]
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-summary-metrics
  labels:
    application: kubernetes
    component: kubelet-summary-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-summary-metrics
subjects:
- kind: ServiceAccount
  name: kubelet-summary-metrics
  namespace: kube-system
# {{ end }}
